version: '3.8'

services:
  nodo1:
    build:
      context: ./nodo1
      dockerfile: Dockerfile
    ports:
      - "1902:9002"
    volumes:
      - dataset:/var/my-data
    depends_on:
      - server
    networks:
      my_network:
        ipv4_address: 172.20.0.2
  nodo2:
    build:
      context: ./nodo2
      dockerfile: Dockerfile
    ports:
      - "2902:9002"
    volumes:
      - dataset:/var/my-data
    depends_on:
      - server
    networks:
      my_network:
        ipv4_address: 172.20.0.3
  nodo3:
    build:
      context: ./nodo3
      dockerfile: Dockerfile
    ports:
      - "3902:9002"
    volumes:
      - dataset:/var/my-data
    depends_on:
      - server
    networks:
      my_network:
        ipv4_address: 172.20.0.4
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4902:9002"
    networks:
      my_network:
        ipv4_address: 172.20.0.5
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5902:8080"
    depends_on:
      - server
    networks:
      my_network:
        ipv4_address: 172.20.0.6
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "6902:3000"
    depends_on:
      - server
    networks:
      my_network:
        ipv4_address: 172.20.0.7
volumes:
  dataset:
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24